create extension if not exists pgcrypto;
create extension if not exists citext;

create table public.tx_fetched (
    id integer primary key generated by default as identity,
    txtimestamp bigint not null,
    chainid bigint not null,
    blockid bigint not null,
    txid varchar(42) not null,
    selector varchar(6) null,
    txfrom varchar(42) not null,
    txto varchar(42),
    txvalue citext,
    txdata citext,
    rawtxbody citext
);


alter table only public.tx_fetched 
    add constraint crosschain_txid unique(chainid, txid);

create index blockid_index on public.tx_fetched using btree (blockid);

create index chainid_index on public.tx_fetched using btree (chainid);

create index txid_index on public.tx_fetched using hash (txid);