create extension if not exists pgcrypto;
create extension if not exists citext;

create table public.interaction (
    id integer primary key generated by default as identity,
    interaction_hash varchar(66) not null,
    chain_id bigint,
    selector varchar(6),
    tx_to varchar(42)
);

create table public.interaction_approve (
    id integer primary key generated by default as identity,
    interaction_hash varchar(66) not null references 
        public.interaction(interaction_hash) on delete cascade,
    eth_address varchar(42) not null,
    message_ citext,
    signature_hex citext
);

create table public.interaction_tx (
    id integer primary key generated by default as identity,
    interaction_hash varchar(66) not null references
        public.interaction(interaction_hash) on delete cascade,
    eth_address varchar(42) not null,
    tx_hash varchar(66) not null,
    block_id bigint not null
);

create table public.moralis_scan_checkpoints (
    id integer primary key generated by default as identity,
    interaction_hash varchar(66) not null references
        public.interaction(interaction_hash) on delete cascade,
    eth_address varchar(42) not null,
    block_id bigint not null
)

alter table only public.interaction
    add constraint interaction_uix unique(chainid, tx_to, selector);

alter table only public.interaction_approve 
    add constraint interaction_approve_approve_uix unique(interaction_hash, eth_address);

alter table only public.interaction_tx
    add constraint interaction_tx_uix unique(interaction_hash, tx_hash);

create index interaction_approve_interaction_hash_index on public.interaction_approve using hash(interaction_hash);

create index interaction_approve_eth_address_index on public.interaction_approve using hash(eth_address);

create index interaction_tx_interaction_hash_index on public.interaction_tx using hash(interaction_hash);

create index interaction_tx_eth_address_index on public.interaction_tx using hash(eth_address);

create index interaction_tx_block_id on public.interaction_tx using btree(block_id);
