version: '3.8'

services:
  backend_api:
    build:
      context: services/backend_api
      dockerfile: ./../../docker/backend_api/Dockerfile
    env_file:
      - ./docker/backend_api/dev.env
    ports:
      - "5000:5000"
    command: ["python", "-m", "app"]
  