version: '3.8'

networks:
  backend:
    name: backend
    external: true

services:
  backend_api:
    build:
      context: services/backend_api
      dockerfile: ./../../docker/backend_api/Dockerfile
    env_file:
      - ./docker/backend_api/dev.env
      - ./docker/postgres/dev.env
    ports:
      - "5050:5050"
    command: ["python", "-m", "app"]
    networks:
      - backend
  # tx_root_publisher:
  #   build:
  #     context: services/tx_root_publisher
  #     dockerfile: ./../../docker/tx_root_publisher/Dockerfile
  #   env_file:
  #     - ./docker/postgres/dev.env
  #     - ./docker/pg_root_publiser
  #   networks:
  #     - backend
