version: '3.8'

networks:
  backend:
    name: backend
    external: true

services:
  postgres:
    image: postgres:14
    container_name: postgres
    ports:
      - '5432:5432'
    command:
      [
        "postgres",
        "-cshared_preload_libraries=pg_stat_statements",
        "-cmax_connections=200"
      ]
    environment:
      PGDATA: "/var/lib/postgresql/data"
      POSTGRES_INITDB_ARGS: "-E UTF8 --locale=C"
    env_file:
      - "./docker/postgres/dev.env"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
      - ./docker/postgres/initdb.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    networks:
      - backend

# todo: pgpool for dc-prod.yml
# todo: bitnami images
